name: cf-pandas
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (don't remove)
  - pytest
  # Examples (remove and add as needed)
  - BeautifulSoup
  - ipywidgets
  - jupyterlab_widgets
  - lxml
  - pandas
  - regex
  - requests
