name: test_env_cf-pandas
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  - pandas
  - regex
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
