name: cf-pandas_docs
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   - pandas
   - regex
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   - sphinx-markdown-tables
   - ipython
   - jinja2
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - recommonmark
   - pip:
     - docrep<=0.2.7
     - furo
     - nbsphinx>=0.8.7
     - jupyter_client
     - sphinx-copybutton
     - sphinxcontrib-srclinks
