#!/bin/bash

set -ex

FILES="docs/demo_*.md"
for f in $FILES
do
  jupytext $f --to ipynb
  <!-- echo "Processing $f file..."
  # take action on each file. $f store current file name
  cat "$f" -->
done

<!-- jupytext demo_reg.md --to ipynb
jupytext demo_vocab.md --to ipynb

invoke build --env-name=root --no-kernel
invoke demofiles
invoke talk -t demo
rm -rf demofiles
rm -rf notebooks
rm -rf narrative
rm -rf slides
rm demo/notebooks/Julia.ipynb
jupyter lab clean

# Setup a workspace
jupyter lab workspaces import binder/workspace.json -->